src/accounts/urls.py
from django.urls import path

from accounts.views import AccountLoginView, AccountLogoutView

app_name = 'accounts'

urlpatterns = [
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('schemas/', include('schemas.urls')),
]

src/schemas/urls.py
from django.urls import path

from schemas.views import SchemaListView, SchemaDeleteView, SchemaCreateView

app_name = 'schemas'

urlpatterns = [
    path('', SchemaListView.as_view(), name='list'),
    path('delete/<int:id>', SchemaDeleteView.as_view(), name='delete'),
    path('create', SchemaCreateView.as_view(), name='create'),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

src/schemas/models.py
from django.db import models


class Schema(models.Model):
    title = models.CharField(max_length=64)
    modify_date = models.DateTimeField(null=True, auto_now=True)

src/schemas/forms.py
from django.forms import ModelForm

from schemas.models import Schema


class SchemaCreateForm(ModelForm):
    class Meta:
        model = Schema
        fields = '__all__'

src/accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.urls import reverse_lazy, reverse


class AccountLoginView(LoginView):
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

src/schemas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, CreateView

from schemas.forms import SchemaCreateForm
from schemas.models import Schema


class SchemaListView(LoginRequiredMixin, ListView):
    model = Schema
    template_name = 'schemas_list.html'
    context_object_name = 'schemas'
    login_url = reverse_lazy('accounts:login')


class SchemaDeleteView(LoginRequiredMixin, DeleteView):
    model = Schema
    success_url = reverse_lazy('schemas:list')
    template_name = 'schemas_delete.html'
    pk_url_kwarg = 'id'
    login_url = reverse_lazy('accounts:login')


class SchemaCreateView(LoginRequiredMixin, CreateView):
    model = Schema
    form_class = SchemaCreateForm
    success_url = reverse_lazy('schemas:list')
    template_name = 'schemas_create.html'
    login_url = reverse_lazy('accounts:login')

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Log in as a user</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Log in">
            <a class="btn btn-light" href="{% url 'index' %}">Back to main page</a>
        </div>
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
<h2>Logout page</h2>
{% endblock %}

{% block main %}
    <a class="btn btn-light" href="{% url 'index' %}">Home</a>
{% endblock %}

src/schemas/templates/includes/schemas_table.html
<table class="table table-hover">
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Modified</th>
        <th>Actions</th>
      </tr>

        {% for schema in schemas %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ schema.title }}</td>
                <td>{{ schema.modify_date|date:'Y-m-d H:i' }}</td>
                <td><a href='{% url "schemas:delete" schema.id %}'>Delete</a></td>
              </tr>
        {% endfor %}

</table>

src/schemas/templates/schemas_create.html
{% extends 'base.html' %}

{% block header %}
    <h2>Create a new data schema</h2>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<form method='post'>
     {% csrf_token %}
     {{ form|crispy }}
     <input type="submit" value="Create">
</form>

{% endblock %}

src/schemas/templates/schemas_delete.html
{% extends 'base.html' %}

{% block header %}
    <h2>Delete data schema</h2>
{% endblock %}

{% block content %}

<form method='post'>
      {% csrf_token %}
      <h3>Do you really want to delete "{{schema.title}}" data schema ?</h3>
      <input type="submit" class="btn btn-danger" value="Delete">
      <a href='{% url "schemas:list" %}' class="btn btn-light">Cancel</a>
</form>

{% endblock %}

src/schemas/templates/schemas_list.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <h1>Data schemas</h1>
{% endblock %}

{% block content %}

{% with schemas=schemas %}
    {% include 'includes/schemas_table.html' %}
{% endwith %}
<a href='{% url "schemas:create" %}' class="btn btn-primary">Create new schema</a>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>CSV Data Generator</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">CSV Data Generator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'schemas:list' %}">Schemas</a>
      </li>
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <ul class="navbar-nav">
            {% if user.is_authenticated %}
                 <span class="navbar-text">Hello, {{ user.username }}</span>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                 </li>
            {% else %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                 </li>
            {% endif %}
        </ul>
    </ul>
  </div>
</nav>

<div class="container">

        <div class="border rounded text-center p-3 m-3 mb-5 shadow">
            {% block header %}
            {% endblock %}
        </div>

        {% block content %}
        {% endblock %}
</div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block header %}
    <h2>Welcome to CSV Data Generator !</h2>
{% endblock %}

{% block main %}
{% endblock %}